version: "3.3"

volumes:
  storage1:

services:
  filedownload:
    container_name: fileDownload
    image: ggg
    restart: always
    ports:
      - "8087:8081"
    volumes:
      - storage1:/usr/src/app/fileDownload
    environment:
      - TZ=Asia/Almaty
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - DOWNLOAD_DOMAIN=192.168.3.86:8087
      - DOWNLOAD_PREFIX=hi
      - SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE=10000MB
      - SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE=10000MB
      - FOLDER_STORAGE_PATH=/usr/src/app/fileDownload/storage
      - SPRING_DATASOURCE_URL=jdbc:sqlite:identifier.sqlite
      - LOGGING_FILE_NAME=./logs/app.log

